const Feed = (channelId: string) => `https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`;

export const NEWS_SOURCES = {
  // International News
  REUTERS: Feed("UChqUTb7kYRX8-EiaN3XFrSQ"),
  AP: Feed("UC52X5wxOL_s5yw0dQk7NtgA"),
  // Technology
  CNET: Feed("UCOmcA3f_RrH6b9NmcNa4tdg"),
  TECH_RADAR: Feed("UCAY_M9HyJb8oMKPV1utQQyA"),
  // Business
  BLOOMBERG: Feed("UCUMZ7gohGI9HcU9VNsr2FJQ"),
  CNBC: Feed("UCvJJ_dzjViJCoLf5uKUTwoA"),
  // Sports
  ESPN: Feed("UCiWLfSweyRNmLpgEHekhoAg"),
  SKY_SPORTS: Feed("UCNAf1k0yIjyGu3k9BwAg3lg"),
  // South African News
  SABC_NEWS: Feed("UC8yH-uI81UUtEMDsowQyx1g"),
  ENCA: Feed("UCI3RT5PGmdi1KVp9FG_CneA"),
  NEWS24: Feed("UC_vRepQuzI527GtEP1pGYZw"),
  NEWSROOM_AFRIKA: Feed("UCQMML3hAsx-Mz9j9ZN0tThQ")
} as const;

export const CATEGORIES = {
  ALL: 'ALL',
  INTERNATIONAL: 'INTERNATIONAL',
  TECHNOLOGY: 'TECHNOLOGY',
  BUSINESS: 'BUSINESS',
  SPORTS: 'SPORTS',
  SOUTH_AFRICAN: 'SOUTH_AFRICAN'
} as const;

// Source to category mapping
export const SOURCE_CATEGORIES = {
  REUTERS: CATEGORIES.INTERNATIONAL,
  AP: CATEGORIES.INTERNATIONAL,
  CNET: CATEGORIES.TECHNOLOGY,
  TECH_RADAR: CATEGORIES.TECHNOLOGY,
  BLOOMBERG: CATEGORIES.BUSINESS,
  CNBC: CATEGORIES.BUSINESS,
  ESPN: CATEGORIES.SPORTS,
  SKY_SPORTS: CATEGORIES.SPORTS,
  SABC_NEWS: CATEGORIES.SOUTH_AFRICAN,
  ENCA: CATEGORIES.SOUTH_AFRICAN,
  NEWS24: CATEGORIES.SOUTH_AFRICAN,
  NEWSROOM_AFRIKA: CATEGORIES.SOUTH_AFRICAN
} as const;
